---
title: "Analyse_stat_Article"
author: "alexandre.williot@uqtr.ca"
date: "05/2023"
output: 
  html_document:
    toc: TRUE
    theme: united
---

#### LEGENDE : 

```{r chargement fichier, include=FALSE}

rm(list=ls())
T<-TRUE
F<-FALSE
# select_incident<-T
# select_P_inter<- T
# select_P_intra<- T

library(readxl)
library(haven)
library(tidyverse) 

# filename_SPSS_1 <- 
#   "C:/Users/utilisateur/Dropbox/2020-2022/1 - Postdoc UQTR/données/projet_Alex_Williot.sav"
# data_SPSS_1 <- read_sav(filename_SPSS_1)

filename_SPSS_1 <- 
  "https://github.com/alexandrewilliot/R-home/raw/main/projet_Alex_Williot.sav"
data_SPSS_1 <- read_sav(filename_SPSS_1)


# filename_SPSS_2 <- 
#   "C:/Users/utilisateur/Dropbox/2020-2022/1 - Postdoc UQTR/données/projet_Alex_Williot_suite.sav"
# data_SPSS_2 <- read_sav(filename_SPSS_2)

filename_SPSS_2 <- 
  "https://github.com/alexandrewilliot/R-home/raw/main/projet_Alex_Williot_suite.sav"
data_SPSS_2 <- read_sav(filename_SPSS_2)


# which(colnames(data_SPSS_1)=="Q12___Estime_corpore_13") #99
# which(colnames(data_SPSS_2)=="Q12___Estime_corpore_13") #99
# which(colnames(data_SPSS_1)=="Q10___Alim__motionne") #85
# which(colnames(data_SPSS_2)=="Q10___Alim__motionne") #85

data_1 <- rbind(data_SPSS_1, data_SPSS_2)

```

```{r library, include=FALSE}
#install.packages("lubridate")
library(lubridate)
library(tidyverse)

library(ltm)#alpha
library(psych)#omega

library(corpcor)
library(GPArotation)

library(boot) # bootstrapping
library(car) # regression diag
library(QuantPsyc) # coeff standard

library(sjmisc) # statistiques descr()

library(Rcmdr)

```


```{r filtre_1, include=FALSE}
# filtrage sur les dates, expérience commence à partir du 8 décembre
data_2<-data_1

#data_2$StartDate
#class(data_2$StartDate) # "POSIXct" "POSIXt" 
data_2$StartDate <- as.Date(data_2$StartDate)
#class(data_2$StartDate) # "Date"
#min(data_2$StartDate) # "2021-11-24"
#max(data_2$StartDate) # "2022-03-06"
data_2 <- subset(data_2, StartDate>"2021-12-7")


# filtre sur colonne données complétes
#which(colnames(data_2)=="Finished") #7
#sum(data_2$Finished) # 689

data_3 <- subset (data_2, Finished > 0 ) # n=689


# filtre sur temps pour faire exp # n=686 pour 300 sec
which(colnames(data_SPSS_1)=="Duration__in_seconds_") #6
data_4 <- subset (data_3, Duration__in_seconds_ > 300 ) #n=686
#data_5 <- subset (data_4, Duration__in_seconds_ > 500 )

#subset (data_5, Duration__in_seconds_ == 501 )
#data_5[ , 43:147]

```

```{r excel data_4, eval=FALSE, include=FALSE}

write.csv2(data_4, "data_4.csv")

```

```{r , include=FALSE}
# filtre sur colonne (pour épurer)

data_5 <- data_4[ , 6:145]
data_5<-data_5[,-c(5:37)] # supression de colonnes

data_6 <- na.omit(data_5) # Supprime toutes les lignes avec des NA #n=578

```


```{r , include=FALSE}
## data 7


#faire traitement des colonnes à part pour ensuite les fusionner avec une colonne mére

data_a <- data_4[ , 1:43]
#data_a <- na.omit(data_)

data_merge <- merge(data_a, data_6, by=c("ResponseId"))

#data_merge <- na.omit(data_merge)


data_7 <- data_merge[ , -c(2:19)]
data_7 <- data_7[ , 1:24]

summary(data_7,  na.rm = TRUE)

names(data_7)[names(data_7) == "Q15"] <- "age"
names(data_7)[names(data_7) == "Q17_1"] <- "homme"
names(data_7)[names(data_7) == "Q17_4"] <- "femme"
names(data_7)[names(data_7) == "Q17_2"] <- "fluctuant"
names(data_7)[names(data_7) == "Q17_3"] <- "nonconf"
names(data_7)[names(data_7) == "Q17_5"] <- "nonbin"
names(data_7)[names(data_7) == "Q19"] <- "niv scol"


# à voir ici pour IMC ; poids, taille
# Q29___Taille_1_TEXT # métre
# Q29___Taille_2_TEXT # pied

# Q30___Poids_1_TEXT # kg
# Q30___Poids_2_TEXT # livres



write.csv2(data_7, "data_7.csv")

# pour aller chercher genre avec ID
csv <- read.csv2("https://github.com/alexandrewilliot/R-home/raw/main/data_stat genre.csv")
csv_2 <- csv[ , 2:4]
# 1 = homme; 2 = femme

data_8 <- merge(csv_2, data_6, by=c("ResponseId"))

# data_6 <- data_8


```


```{r poids taille, include=FALSE}

csv_3 <- read.csv2("https://github.com/alexandrewilliot/R-home/raw/main/data_stat genre_Carolanne.csv")
which(colnames(csv_3)=="poids.en.kg.1") #30
which(colnames(csv_3)=="Taille.en.cm") #25

# Reorder Columns of Data Frame by Index - changer position
csv_3 <- csv_3[ , c(2,25,30, 1, 3:24, 26:29  )]
csv_4 <- csv_3[ , 1:3]

data_8b <- merge(csv_4, data_8, by=c("ResponseId"))


data_6 <- data_8b
```

```{r IMC, include=FALSE}

# Fichier 6 prêt
# voir calcul IMC
data_6$IMC <- data_6$poids.en.kg.1 / (data_6$Taille.en.cm*data_6$Taille.en.cm)
data_6$IMC <- data_6$IMC*10000

data_6 <- data_6[ , c(1:3 , 112, 4:111 )]


# vérifier validité des données
data_b <- subset (data_6, poids.en.kg.1 < 50 ) # 1 ligne ; pas si pire

data_c <- subset (data_6, age < 12 ) # 54 lignes ; 

data_d <- subset (data_6, Taille.en.cm < 110 ) # 1 ligne ; pas si pire


summary(data_6,  na.rm = TRUE)

```

### stat age

```{r recode âge, include=FALSE}

data_6$age <- recode(data_6$age, "1=18; 2=19; 3=20;4=21; 5=22; 6=23; 7=24 ; 8=25; 9=26 ; 10=27 ; 11=28; 12=29; 13=30; 14=31; 15=32; 16=33; 17=34; 18=35 ; 19=36 ; 20=37; 21=38; 22=39 ; 23=40; 24=41 ; 25=42; 26=43; 27=44; 28=45 ; 29=46; 30=47; 31=48; 32=49; 33=50 ; 34=51; 35=52; 36=53; 37=54; 38=55; 39=56; 40=57; 41=58; 42=59; 43=60; 44=61; 45=62; 46=63; 47=64; 48=65; 49=66; 50=67; 51=68; 52=69; 53=70; 54=71; 55=72; 56=73; 57=74; 58=75; 59=76; 60=77; 61=78; 62=79; 63=80; 64=81;65=82; 66=83; 67=84; 68=85; 69=86; 70=87; 71=88; 72=89; 73=90; 74=91; 75=92; 76=93; 77=94; 78=95; 79=96; 80=97; 81=98; 82=99; 83=100")

```

```{r age, echo=FALSE}
summary(data_6$age)
sd(data_6$age)
numSummary(data_6[,"age", drop=FALSE], statistics=c("mean", "sd"), type="2")

```



### stat imc # par catégories

```{r stat, echo=FALSE}
numSummary(data_6[,"IMC", drop=FALSE], statistics=c("mean", "sd"), type="2")

max(data_6$IMC, na.rm = TRUE)
#sort(data_6$IMC)

# plus de 40 obésite morbide
data_6$IMC_2 <- as.factor(ifelse(data_6$IMC < 18.5, '1',
                                 ifelse(data_6$IMC < 25, '2', 
                                        ifelse(data_6$IMC < 30, '3', 
                                               ifelse(data_6$IMC < 35, '4',
                                                      ifelse(data_6$IMC < 40, '5',
                                                             ifelse(data_6$IMC > 40, '6',
                                                             7)))))))
data_6 <- data_6[ , c(1:3 , 113, 4:112 )]
#max(data_6$IMC)

numSummary(data_6[,"IMC", drop=FALSE], data_6$IMC_2, statistics=c("mean", "sd", "IQR", "quantiles", "skewness", "kurtosis"), quantiles=c(0,.25,.5,.75,1), type="2")


#data_6a<-data_6[!is.na(data_6$IMC), ] # supprime lignes avec des NA dans une colonne
#max(data_6a$IMC)


```

```{r subset imc, include=FALSE}

subset_imc <- subset(data_6, IMC > 40) # au dessus de la catégorie 5 donc que des 6

```


### Questionnaires



```{r CERQ 1, include=FALSE}
#score aux questionnaires
#CERQ

#somme

data_6$CERQ_ACC <- data_6$Q6___R_gulation_cogn_1 + data_6$Q6___R_gulation_cogn_5
data_6$CERQ_RUM <- data_6$Q6___R_gulation_cogn_2 + data_6$Q6___R_gulation_cogn_6
data_6$CERQ_REA <- data_6$Q6___R_gulation_cogn_3 + data_6$Q6___R_gulation_cogn_8
data_6$CERQ_CUL <- data_6$Q6___R_gulation_cogn_4 + data_6$Q6___R_gulation_cogn_14
data_6$CERQ_REC <- data_6$Q6___R_gulation_cogn_7 + data_6$Q6___R_gulation_cogn_11
data_6$CERQ_DRA <- data_6$Q6___R_gulation_cogn_9 + data_6$Q6___R_gulation_cogn_17
data_6$CERQ_BLA <- data_6$Q6___R_gulation_cogn_10 + data_6$Q6___R_gulation_cogn_18
data_6$CERQ_PLA <- data_6$Q6___R_gulation_cogn_12 + data_6$Q6___R_gulation_cogn_15
data_6$CERQ_PERS <- data_6$Q6___R_gulation_cogn_13 + data_6$Q6___R_gulation_cogn_16

#moyenne
data_6$CERQ_MAL <- (data_6$CERQ_CUL + data_6$CERQ_BLA + data_6$CERQ_RUM + data_6$CERQ_DRA)/8 

data_6$CERQ_ADA <- (data_6$CERQ_ACC + data_6$CERQ_REA + data_6$CERQ_REC + data_6$CERQ_PLA + data_6$CERQ_PERS)/10

```

```{r CERQ 2, include=FALSE}
#moyenne

data_6$CERQ_ACC <- (data_6$Q6___R_gulation_cogn_1 + data_6$Q6___R_gulation_cogn_5)/2
data_6$CERQ_RUM <- (data_6$Q6___R_gulation_cogn_2 + data_6$Q6___R_gulation_cogn_6)/2
data_6$CERQ_REA <- (data_6$Q6___R_gulation_cogn_3 + data_6$Q6___R_gulation_cogn_8)/2
data_6$CERQ_CUL <- (data_6$Q6___R_gulation_cogn_4 + data_6$Q6___R_gulation_cogn_14)/2
data_6$CERQ_REC <- (data_6$Q6___R_gulation_cogn_7 + data_6$Q6___R_gulation_cogn_11)/2
data_6$CERQ_DRA <- (data_6$Q6___R_gulation_cogn_9 + data_6$Q6___R_gulation_cogn_17)/2
data_6$CERQ_BLA <- (data_6$Q6___R_gulation_cogn_10 + data_6$Q6___R_gulation_cogn_18)/2
data_6$CERQ_PLA <- (data_6$Q6___R_gulation_cogn_12 + data_6$Q6___R_gulation_cogn_15)/2
data_6$CERQ_PERS <- (data_6$Q6___R_gulation_cogn_13 + data_6$Q6___R_gulation_cogn_16)/2

```



```{r AI, include=FALSE}
# Alimentation intuitive ; carbonneau 2016
# 7 items inversé : 1,2,4,5,9,10,11 
# j'ai vérifié avec tylka 2013 que c'était les bons items, ok même si numéro pas relié avec la publication ici.

data_6$Q7___Alim_intuitive_1 <- recode(data_6$Q7___Alim_intuitive_1, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q7___Alim_intuitive_2 <- recode(data_6$Q7___Alim_intuitive_2, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q7___Alim_intuitive_4 <- recode(data_6$Q7___Alim_intuitive_4, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q7___Alim_intuitive_5 <- recode(data_6$Q7___Alim_intuitive_5, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q7___Alim_intuitive_9 <- recode(data_6$Q7___Alim_intuitive_9, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q7___Alim_intuitive_10 <- recode(data_6$Q7___Alim_intuitive_10, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q7___Alim_intuitive_11 <- recode(data_6$Q7___Alim_intuitive_11, "1=5; 2=4; 3=3;4=2; 5=1")

# faire moyenne de l'échelle et sous-échelles pour obtenir score

#str(data_6)
# unconditional permission to eat
data_6$AI_UPE <- (data_6$Q7___Alim_intuitive_1 + data_6$Q7___Alim_intuitive_3 + data_6$Q7___Alim_intuitive_4 + data_6$Q7___Alim_intuitive_9 + data_6$Q7___Alim_intuitive_16 + data_6$Q7___Alim_intuitive_17)/6

#eating for physical reason than emotional
data_6$AI_EPPR <- (data_6$Q7___Alim_intuitive_2 + data_6$Q7___Alim_intuitive_5 + data_6$Q7___Alim_intuitive_10 + data_6$Q7___Alim_intuitive_11 + data_6$Q7___Alim_intuitive_12 + data_6$Q7___Alim_intuitive_13 + data_6$Q7___Alim_intuitive_14 + data_6$Q7___Alim_intuitive_15)/8

#Reliance on hunger and satiety cues
data_6$AI_RHSC <- (data_6$Q7___Alim_intuitive_6 + data_6$Q7___Alim_intuitive_7 + data_6$Q7___Alim_intuitive_8 + data_6$Q7___Alim_intuitive_21 + data_6$Q7___Alim_intuitive_22 + data_6$Q7___Alim_intuitive_23)/6

#body food choice
data_6$AI_BFC <- (data_6$Q7___Alim_intuitive_18 + data_6$Q7___Alim_intuitive_19 + data_6$Q7___Alim_intuitive_20 )/3


# TOTAL
data_6$AI_total <- (data_6$Q7___Alim_intuitive_1 + data_6$Q7___Alim_intuitive_2 + data_6$Q7___Alim_intuitive_3 + data_6$Q7___Alim_intuitive_4 + data_6$Q7___Alim_intuitive_5 + data_6$Q7___Alim_intuitive_6 + data_6$Q7___Alim_intuitive_7 + data_6$Q7___Alim_intuitive_8 + data_6$Q7___Alim_intuitive_9 + data_6$Q7___Alim_intuitive_10 + data_6$Q7___Alim_intuitive_11 + data_6$Q7___Alim_intuitive_12 + data_6$Q7___Alim_intuitive_13 + data_6$Q7___Alim_intuitive_14 + data_6$Q7___Alim_intuitive_15 + data_6$Q7___Alim_intuitive_16 + data_6$Q7___Alim_intuitive_17 + data_6$Q7___Alim_intuitive_18 + data_6$Q7___Alim_intuitive_19 + data_6$Q7___Alim_intuitive_20 + data_6$Q7___Alim_intuitive_21 + data_6$Q7___Alim_intuitive_22 + data_6$Q7___Alim_intuitive_23)/23

```

```{r BE, include=FALSE}
# body esteem - valls 2011

#inversion des scores des items 4, 7, 9, 11, 13, 17, 18, 19 et 21 

data_6$Q12___Estime_corpore_4 <- recode(data_6$Q12___Estime_corpore_4, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q12___Estime_corpore_7 <- recode(data_6$Q12___Estime_corpore_7, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q12___Estime_corpore_9 <- recode(data_6$Q12___Estime_corpore_9, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q12___Estime_corpore_11 <- recode(data_6$Q12___Estime_corpore_11, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q12___Estime_corpore_13 <- recode(data_6$Q12___Estime_corpore_13, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q12___Estime_corpore_17 <- recode(data_6$Q12___Estime_corpore_17, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q12___Estime_corpore_18 <- recode(data_6$Q12___Estime_corpore_18, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q12___Estime_corpore_19 <- recode(data_6$Q12___Estime_corpore_19, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q12___Estime_corpore_21 <- recode(data_6$Q12___Estime_corpore_21, "1=5; 2=4; 3=3;4=2; 5=1")


#somme


# « Apparence » fait référence aux sentiments généraux envers l’apparence corporelle et comprend dix items (1-6-7-9-11- 13-15-17-21-23)
data_6$BE_APP <- data_6$Q12___Estime_corpore_1 + data_6$Q12___Estime_corpore_6 + data_6$Q12___Estime_corpore_7 + data_6$Q12___Estime_corpore_9 + data_6$Q12___Estime_corpore_11 + data_6$Q12___Estime_corpore_13 + data_6$Q12___Estime_corpore_15 + data_6$Q12___Estime_corpore_17 + data_6$Q12___Estime_corpore_21 + data_6$Q12___Estime_corpore_23

# « L’Attribution », composée de cinq items (2-5-12-14-20), correspond aux croyances concernant la fac¸on dont leur apparence corporelle est perc¸ue par les autres.
data_6$BE_ATT <- data_6$Q12___Estime_corpore_2 + data_6$Q12___Estime_corpore_5 + data_6$Q12___Estime_corpore_12 + data_6$Q12___Estime_corpore_14 + data_6$Q12___Estime_corpore_20

#« Poids » évalue la satisfaction ou l’insatisfaction envers le poids et comprend huit items (3- 4-8-10-16-18-19-22).
data_6$BE_Poids <- data_6$Q12___Estime_corpore_3 + data_6$Q12___Estime_corpore_4 + data_6$Q12___Estime_corpore_8 + data_6$Q12___Estime_corpore_10 + data_6$Q12___Estime_corpore_16 + data_6$Q12___Estime_corpore_18 + data_6$Q12___Estime_corpore_19 + data_6$Q12___Estime_corpore_22


data_6$BE_total <- (data_6$BE_APP + data_6$BE_ATT + data_6$BE_Poids)/23

#moyenne


# « Apparence » fait référence aux sentiments généraux envers l’apparence corporelle et comprend dix items (1-6-7-9-11- 13-15-17-21-23)
data_6$BE_APP <- (data_6$Q12___Estime_corpore_1 + data_6$Q12___Estime_corpore_6 + data_6$Q12___Estime_corpore_7 + data_6$Q12___Estime_corpore_9 + data_6$Q12___Estime_corpore_11 + data_6$Q12___Estime_corpore_13 + data_6$Q12___Estime_corpore_15 + data_6$Q12___Estime_corpore_17 + data_6$Q12___Estime_corpore_21 + data_6$Q12___Estime_corpore_23)/10

# « L’Attribution », composée de cinq items (2-5-12-14-20), correspond aux croyances concernant la fac¸on dont leur apparence corporelle est perc¸ue par les autres.
data_6$BE_ATT <- (data_6$Q12___Estime_corpore_2 + data_6$Q12___Estime_corpore_5 + data_6$Q12___Estime_corpore_12 + data_6$Q12___Estime_corpore_14 + data_6$Q12___Estime_corpore_20)/5

#« Poids » évalue la satisfaction ou l’insatisfaction envers le poids et comprend huit items (3- 4-8-10-16-18-19-22).
data_6$BE_Poids <- (data_6$Q12___Estime_corpore_3 + data_6$Q12___Estime_corpore_4 + data_6$Q12___Estime_corpore_8 + data_6$Q12___Estime_corpore_10 + data_6$Q12___Estime_corpore_16 + data_6$Q12___Estime_corpore_18 + data_6$Q12___Estime_corpore_19 + data_6$Q12___Estime_corpore_22)/8



```

```{r EE, include=FALSE}
#emotional eating

which(colnames(data_6)=="Q9___Alim__motionnel")

names(data_6)[names(data_6) == "Q9___Alim__motionnel"] <- "Q9_Alim_emotionnel"
names(data_6)[names(data_6) == "Q10___Alim__motionne"] <- "Q10_Alim_emotionnel"
names(data_6)[names(data_6) == "Q11___Alim__motionne"] <- "Q11_Alim_emotionnel"

data_6$EE <- (data_6$Q9_Alim_emotionnel + data_6$Q10_Alim_emotionnel + data_6$Q11_Alim_emotionnel)/3

```

```{r interna, include=FALSE}
#Internalisation des normes sociales d’apparence 
#Rousseau et al (2010) ; Validation of the French version of the Sociocultural Attitudes Towards Appearance Scale-3 (SATAQ-3) ; items : 3, 4, 7, 8, 11, 12, 15, 16, 27 de l'échelle originale

# internalisation générale

data_6$Interna <- (data_6$Q13___Internalisatio_1 + data_6$Q13___Internalisatio_2 + data_6$Q13___Internalisatio_3 + data_6$Q13___Internalisatio_4 + data_6$Q13___Internalisatio_5 + data_6$Q13___Internalisatio_6 + data_6$Q13___Internalisatio_7 + data_6$Q13___Internalisatio_8 + data_6$Q13___Internalisatio_9)/9
```




```{r QSREIC, include=FALSE}
# calcul sous-dim du QSREIC

#somme

#dramatisation : 4 items
data_6$QSREIC_dramatisation <- data_6$Q14___QSREIC_1 + data_6$Q14___QSREIC_9 + data_6$Q14___QSREIC_14 + data_6$Q14___QSREIC_17

#planification : 4 items
data_6$QSREIC_planif <- data_6$Q14___QSREIC_2 + data_6$Q14___QSREIC_11 + data_6$Q14___QSREIC_12 + data_6$Q14___QSREIC_25

#recentrage : 3 items
data_6$QSREIC_recentrage <- data_6$Q14___QSREIC_3 + data_6$Q14___QSREIC_7 + data_6$Q14___QSREIC_18 

#social : 4 items
#reverse items 8

data_6$Q14___QSREIC_5 <- recode(data_6$Q14___QSREIC_5, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q14___QSREIC_19 <- recode(data_6$Q14___QSREIC_19, "1=5; 2=4; 3=3;4=2; 5=1")
data_6$Q14___QSREIC_26 <- recode(data_6$Q14___QSREIC_26, "1=5; 2=4; 3=3;4=2; 5=1")

data_6$QSREIC_social <- data_6$Q14___QSREIC_5 + data_6$Q14___QSREIC_8 + data_6$Q14___QSREIC_19 + data_6$Q14___QSREIC_26

#culpa : 2 items
data_6$QSREIC_culpa <- data_6$Q14___QSREIC_6 + data_6$Q14___QSREIC_13

#refus : 4 items
data_6$QSREIC_refus <- data_6$Q14___QSREIC_10 + data_6$Q14___QSREIC_16 + data_6$Q14___QSREIC_21 + data_6$Q14___QSREIC_24

#rumination: 
data_6$QSREIC_rumination <- data_6$Q14___QSREIC_22 

#physique: 2 items
data_6$QSREIC_physique<- data_6$Q14___QSREIC_23 + data_6$Q14___QSREIC_4

#évitement: 3 items
data_6$QSREIC_évitement <- data_6$Q14___QSREIC_27 + data_6$Q14___QSREIC_20 +  data_6$Q14___QSREIC_15


data_6$QSREIC_ADA <- (data_6$QSREIC_planif + data_6$QSREIC_recentrage + data_6$QSREIC_social + data_6$QSREIC_refus) /15

data_6$QSREIC_MAL <- (data_6$QSREIC_dramatisation + data_6$QSREIC_physique + data_6$QSREIC_culpa + data_6$QSREIC_rumination + data_6$QSREIC_évitement)/12



#moyenne

#dramatisation : 4 items
data_6$QSREIC_dramatisation <- (data_6$Q14___QSREIC_1 + data_6$Q14___QSREIC_9 + data_6$Q14___QSREIC_14 + data_6$Q14___QSREIC_17)/4

#planification : 4 items
data_6$QSREIC_planif <- (data_6$Q14___QSREIC_2 + data_6$Q14___QSREIC_11 + data_6$Q14___QSREIC_12 + data_6$Q14___QSREIC_25)/4

#recentrage : 3 items
data_6$QSREIC_recentrage <- (data_6$Q14___QSREIC_3 + data_6$Q14___QSREIC_7 + data_6$Q14___QSREIC_18 )/3

#social : 4 items
data_6$QSREIC_social <- (data_6$Q14___QSREIC_5 + data_6$Q14___QSREIC_8 + data_6$Q14___QSREIC_19 + data_6$Q14___QSREIC_26)/4

#culpa : 2 items
data_6$QSREIC_culpa <- (data_6$Q14___QSREIC_6 + data_6$Q14___QSREIC_13)/2

#refus : 4 items
data_6$QSREIC_refus <- (data_6$Q14___QSREIC_10 + data_6$Q14___QSREIC_16 + data_6$Q14___QSREIC_21 + data_6$Q14___QSREIC_24)/4

#rumination: 
data_6$QSREIC_rumination <- data_6$Q14___QSREIC_22 

#physique: 2 items
data_6$QSREIC_physique<- (data_6$Q14___QSREIC_23 + data_6$Q14___QSREIC_4)/2

#évitement: 3 items
data_6$QSREIC_évitement <- (data_6$Q14___QSREIC_27 + data_6$Q14___QSREIC_20 +  data_6$Q14___QSREIC_15)/3


```


## statistiques descriptives des questionnaires

```{r , echo=FALSE}
data_9 <- data_6[ , -c(8:113)]

# moy des variables par genre
a <- data_9 %>% 
  group_by(genre) %>% 
  summarise(CERQ_MAL = mean(CERQ_MAL),
            CERQ_ADA  = mean(CERQ_ADA),
            AI_total  = mean(AI_total),
            BE_total  = mean(BE_total),
            EE  = mean(EE),
            Interna  = mean(Interna),
            QSREIC_ADA  = mean(QSREIC_ADA),
            QSREIC_MAL  = mean(QSREIC_MAL))
#write.csv2(data_9, "data_9_quest.csv")
#vérif ok

a

b <- data_9 %>% 
  group_by(genre) %>% 
  summarise(CERQ_MAL = sd(CERQ_MAL),
            CERQ_ADA  = sd(CERQ_ADA),
            AI_total  = sd(AI_total),
            BE_total  = sd(BE_total),
            EE  = sd(EE),
            Interna  = sd(Interna),
            QSREIC_ADA  = sd(QSREIC_ADA),
            QSREIC_MAL  = sd(QSREIC_MAL))
b

```




## STOP plus bon aprés
### Alpha à voir à partir autres scripts


```{r excel data_6, include=FALSE}

write.csv2(data_6, "data_6.csv")

write_sav(data_6, "data_6.sav")
```



```{r, echo=FALSE}

#voir pour valider échelle - AF pour QSREIC
#voir Boateng (2018) et akena (2018)

#http://rstudio-pubs-static.s3.amazonaws.com/11011_caa8639a12cb488aba3df58c696626bb.html

# voir pour passer en EQS

#voir path 2017

```


