---
title: "Resultats Projet Noemie"
author: "alexandre.williot@uqtr.ca"
date: "06/2022"
output: 
  html_document:
    toc: TRUE
    theme: united


---

******************************************************************************

# hommes et femmes (n=578)
## Resultats basés sur échelle originale - 27 items
#### alpha faible pour planif, drama, culpa
#### adaptatif = 0.82 ; maladaptatif = 0.79
[file here:] (https://alexandrewilliot.github.io/R-home/Analyse.html)

## Resultats SANS sous-échelle planif, drama, culpa (alpha faible)
#### adaptatif = 0.83 ; maladaptatif = 0.75
[file here:] (https://alexandrewilliot.github.io/R-home/Analyse_QSREIC.html)

## Resultats avec nouvelles sous-échelles (5) (aprés Analyse factorielle)
#### adaptatif = 0.88 ; maladaptatif = 0.61
[file here:] (https://alexandrewilliot.github.io/R-home/Analyse_QSREIC_AF.html)

## Resultats avec 2 facteurs pour analyse factorielle (échelle originale 27 items)
#### 37% de variance cumulé
[file here:] (https://alexandrewilliot.github.io/R-home/Analyse_2facteurs.html)

## Resultats avec 2 facteurs pour analyse factorielle (échelle modifié)
#### aprés avoir retiré les items présents aux 2 facteurs de la même façon (9,17,25) et adapté alpha mal et ada selon analyse factorielle ## Résultats VALIDES QUE POUR ALPHA MAL ET ADA ET AF !
#### d'autres items se placent sur les 2 facteurs
[file here:] (https://alexandrewilliot.github.io/R-home/Analyse_2facteurs_select.html)

## Resultats avec 2 facteurs pour analyse factorielle (échelle modifié 2)
#### aprés avoir retiré les items présents aux 2 facteurs (9,17,25,10,18,16,8) et adapté alpha mal et ada selon analyse factorielle ## Résultats VALIDES QUE POUR ALPHA MAL ET ADA ET AF !
#### adaptatif = 0.66 ; maladaptatif = 0.87
[file here:] (https://alexandrewilliot.github.io/R-home/Analyse_2facteurs_select_2.html)

# femmes
## Resultats basés sur échelle originale - 27 items
[file here:] (https://alexandrewilliot.github.io/R-home/Analyse_F.html)


